### ISSUE TITLE
ucharmap

### ISSUE THREAD

**Issue by shmuz** [m32/far2lpython#1]
Hello,
I'm observing an issue with `ucharmap`: it runs OK when far is launched with `--tty` but nothing happens when far is run in GUI mode and the utility is invoked from the plugins menu.

I enabled the debug output in far and this is what it prints on attempt to invoke ucharmap from the plugins menu:
```
ERROR:far2l.pluginmanager:Uncaught exception
Traceback (most recent call last):
  File "/home/shmuel/far2m/_build/install/Plugins/python/plug/far2l/pluginmanager.py", line 249, in OpenPlugin
    rc = plugin.OpenPlugin(OpenFrom)
  File "/home/shmuel/far2m/_build/install/Plugins/python/plug/plugins/ucharmap.py", line 344, in OpenPlugin
    def DialogProc(hDlg, Msg, Param1, Param2):
  File "/home/shmuel/far2m/_build/install/Plugins/python/plug/python/lib/python3.8/site-packages/cffi/api.py", line 396, in callback_decorator_wrap
    return self._backend.callback(cdecl, python_callable,
SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
```

**Comment by m32** [comment]
I had the same after updating ubuntu packages. Recompiling the python ffi library from sources helped me: pypi cffi is from Jun 30, 2022 but libffi is newer:

https://pypi.org/project/cffi/#files and then cffi-1.15.1.tar.gz

**Comment by shmuz** [comment]
Thank you,
but I'm afraid I won't be able to do that without a detailed instruction.

P.S.
I downloaded and unpacked `cffi-1.15.1.tar.gz` then ran
`sudo python3 ./setup.py install`
then restarted Linux. The behavior is the same.

**Comment by m32** [comment]
download and unpack this file, later run:
 python setup.py build_ext
 python setup.py install

python=/home/shmuel/far2m/_build/install/Plugins/python/bin/python

**Comment by m32** [comment]
@shmuz sudo python3 invokes system wide interpreter, but python plugin has its own

**Comment by m32** [comment]
https://stackoverflow.com/questions/62658237/it-seems-that-the-version-of-the-libffi-library-seen-at-runtime-is-different-fro

$ sudo apt install libffi-dev
$ /home/shmuel/far2m/_build/install/Plugins/python/bin/pip install --force-reinstall --no-binary :all: cffi

**Comment by shmuz** [comment]
I'm sorry to waste your time but still no luck.
And I wonder why charmap works when far is started in TTY mode.
```
...m/_build/install/Plugins/python/plug/python/bin$ ./pip install --force-reinstall --no-binary :all: cffi↑
Collecting cffi
  Downloading cffi-1.15.1.tar.gz (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.5/508.5 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pycparser (from cffi)
  Downloading pycparser-2.21.tar.gz (170 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: cffi, pycparser
  Building wheel for cffi (setup.py) ... done
  Created wheel for cffi: filename=cffi-1.15.1-cp38-cp38-linux_x86_64.whl size=376821 sha256=ed3d6b65324a57
ea6ce3e2334ebd67c267df2527c842a818ef60180f48be28c3
  Stored in directory: /home/shmuel/.cache/pip/wheels/4f/6c/1c/87e97bb9c55afbf66881d37eed21c108b012c29105af
6be450
  Building wheel for pycparser (setup.py) ... done
  Created wheel for pycparser: filename=pycparser-2.21-py2.py3-none-any.whl size=118699 sha256=df2fb9413043
24ab5bdbb4fa74cc7e01fcdd63816d3a71d75f2caebc96bba3f4
  Stored in directory: /home/shmuel/.cache/pip/wheels/e2/21/1d/cb7e83fcb949aa151b65acb6860b70f37e4c22594561
ed2375
Successfully built cffi pycparser
Installing collected packages: pycparser, cffi
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.21
    Uninstalling pycparser-2.21:
      Successfully uninstalled pycparser-2.21
  Attempting uninstall: cffi
    Found existing installation: cffi 1.15.1
    Uninstalling cffi-1.15.1:
      Successfully uninstalled cffi-1.15.1
Successfully installed cffi-1.15.1 pycparser-2.21
```

**Comment by m32** [comment]
according to me, starting with wx or tty has no impact on python

try installing cffi manually, step by step, by downloading cffi..tar.gz and compiling:
/home/shmuel/far2m/_build/install/Plugins/python/bin/python setup.py build_ext
# and installing
/home/shmuel/far2m/_build/install/Plugins/python/bin/python  setup.py install
# at end run far2l
/home/shmuel/far2m/_build/install/far2l

If you have already installed far2l then you need to use a different prefix

**Comment by shmuz** [comment]
Thank you for your help!

All my attempts have failed.
Most probably (being a not experienced Linux user) I'm doing something wrong.
However my main goal was not `ucharmap` plugin itself but rather:
1. to make sure my far2m (a far2l fork) isn't broken (it is not as far2l behaves the same way with regards to `ucharmap`)
2. to learn something about Python plugins

Speaking about TTY versus WX: theoretically it has nothing to do with Python but the fact is `ucharmap` runs under TTY and does not under WX.

I hope some day I'll be able to run `ucharmap` under WX.

**Comment by m32** [comment]
:(
last chance ? - enable far logging and recompile python plugin with log enabled in python.cpp #define PYPLUGIN_DEBUGLOG

export FAR2L_STD=/tmp/far2l.log
far2l $*

**Comment by shmuz** [comment]
The last chance was a success!
`ucharmap` works under WX and no exception is observed.

The step I was missing in my previous attempts was rebuilding the Python plugin.
Thank you very much!

**Comment by m32** [comment]
nice to hear that, powodzenia :)

**Comment by shmuz** [comment]
Wzajemnie
(no I don't speak Polish :)
