### ISSUE TITLE
A definition that cffi cannot cope with

### ISSUE THREAD

**Issue by shmuz** [m32/far2lpython#2]
[far2m issue]
Recently I added a new definition to `farplug-wide.h` that caused the Python plugin to stop function:
```C
struct VersionInfo
{
	DWORD Major;
	DWORD Minor;
	DWORD Revision;
	DWORD Build;
};

static __inline struct VersionInfo MAKEPLUGVERSION(DWORD Major, DWORD Minor, DWORD Revision, DWORD Build)
{
	struct VersionInfo Info = {Major, Minor, Revision, Build};
	return Info;
}
```
When I run far2m with printf enabled I see a Python exception telling that cffi is  unable to parse the `MAKEPLUGVERSION` definition.
The question: is there a way to tell cffi not to parse some code part, e.g. by a preprocessor `#if ... #endif` ?

**Comment by m32** [comment]
cffi for python doesn't like inline definitions, it's better to use #define
In my opinion it's best to disable it with the preprocessor definition #if !defined(FAR_PYTHON_GEN), the same should be possible with function declarations exported from the plugin.

**Comment by shmuz** [comment]
Excellent!  `FAR_PYTHON_GEN` works and this is exactly what I wanted.

Yes it is possible to define `MAKEPLUGVERSION` as a macro, but the syntax would be much less beautiful.

**Comment by shmuz** [comment]
I have another question, that must be an easy one.
I add to each 3-rd party plugin a file `GlobalInfo.cpp` thet looks like following (for the Python plugin):
```C
#include <farplug-wide.h>

SHAREDSYMBOL void WINAPI EXP_NAME(GetGlobalInfo)(struct GlobalInfo *aInfo)
{
  aInfo->StructSize    = sizeof(*aInfo);
  aInfo->SysID         = 0x7E9585C2;
  aInfo->Version       = MAKEPLUGVERSION(0,0,0,0);
  aInfo->Title         = L"Python";
  aInfo->Description   = L"Python plugin for Far Manager";
  aInfo->Author        = L"Grzegorz Makarewicz";
}
```
If you'd like me to correct something, please tell :)

**Comment by m32** [comment]
I expose all exported functions to python and process them there at the level of the plugin manager, in this case I would also do it this way - eg. place to set plugin version should be in python code and not in C code
SysID - is it about this variable and its value?
Sort of compatibility with FAR3 in Lua plugin ?

**Comment by shmuz** [comment]
> eg. place to set plugin version should be in python code and not in C code

I did it in my Lua plugins for Far3 (i.e. GlobalInfo was in Lua code). But later I understood that it doesn't matter and such info is better kept in a separate file. But you don't have to agree :)

>SysID - is it about this variable and its value?
> Sort of compatibility with FAR3 in Lua plugin ?

This variable existed in Far2 and far2l, I didn't invent it.
This is a plugin unique identifier that makes possible to call plugin's functions from Far Manager macros.
It is a very powerful feature.

**Comment by shmuz** [comment]
![image](https://github.com/m32/far2lpython/assets/344558/6d9854d1-21da-4d91-a18b-8ab93991187e)

**Comment by m32** [comment]
ok, so let's leave it in C code.
A python plugin is a multi plugin and setting sysid on it won't tell it which python plugin should handle the macro.
Let's assume that you write the plugin in Python, so the author is not me, but you, and the image will show something completely different.

**Comment by shmuz** [comment]
Macros in far2m are like in Far3, they are orders of magnitude more powerful than in far2l.
When one calls the plugin from a macro it is possible to pass any number of arguments telling exactly what should be done.

> Let's assume that you write the plugin in Python, so the author is not me, but you, and the image will show something completely different.

You're right but this is the thing that can be addressed in the future.

**Comment by m32** [comment]
I would leave it in C. At this stage, I don't know what will happen later, and for the plugin it doesn't interfere with anything.

**Comment by shmuz** [comment]
Due to lack of time I decided not to maintain plugins other than mine.
So far2l plugins I take from far2l (almost) "as is".
If you don't mind to include GlobalInfo.cpp in your plugin (it won't interfere with far2l), I'll be happy.
It is 1 additional file in src directory and 1 line added to CMakeLists.txt.
But if you don't... I will accept it the same way :)

P.S. I was not right. far2l's farplug-wide.h doesn't have GlobalInfo and MAKEPLUGVERSION definitions.
But if you in principle agree, I will handle that with ease (it is a matter of one `#if ... #endif`).

**Comment by shmuz** [comment]
Done already: https://github.com/shmuz/far2m/blob/master/python/src/GlobalInfo.cpp

**Comment by shmuz** [comment]
As the issue is resolved, I'm closing it. Thank you.
